---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:

    controller_auth_user: "a.user@f5.com"
    controller_auth_password: "Password1"
    controller_domain_name: "controller.workshop0001.nginxdemo.net"
    controller_api_version: "v1"

    controller_user_request_body:
      username: "a.userf5.com"
      password: "Password1"

    gateway1_target_ip:   10.0.1.20
    gateway2_target_ip:   10.0.1.30      
    apibackend_target_ip: 10.0.1.90      
    

  tasks:
      

    - name: Log into NGINX Controller
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/platform/login
        method: POST
        body_format: json 
        body: 
          credentials: 
            type: "BASIC"
            username: "{{ controller_auth_user }}"
            password: "{{ controller_auth_password }}"
        status_code: 204
        validate_certs: false
      register: session

    - name: Store session cookie as fact
      set_fact:
        nginx_controller_session: "{{ session }}"


    - name: Work out which of the three instantiated NGINX instances are destined to be gateway 1, gateway2 and the apibackend
      uri:
        url: https://{{ controller_domain_name }}/api/v1/infrastructure/locations/unspecified/instances
        method: GET
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:
          nullfield: "null"
        status_code: 200
        validate_certs: false
      register: instances
      
    - name: Store the list of instances as a fact
      set_fact:
        nginx_server_instances: "{{ instances }}"

    - name: Debugging info 1
      debug:
        msg: "Instance IP address: {{ nginx_server_instances.json['items'][0].currentStatus.legacySystemMetadata.network.interfaces[1].ipv4.address}} has instance ID: {{ nginx_server_instances.json['items'][0].metadata.name}}"
        
    - name: Debugging info 2
      debug:        
        msg: "Instance IP address: {{ nginx_server_instances.json['items'][1].currentStatus.legacySystemMetadata.network.interfaces[1].ipv4.address}} has instance ID: {{ nginx_server_instances.json['items'][1].metadata.name}}"
        
    - name: Debugging info 3
      debug:
        msg: "Instance IP address: {{ nginx_server_instances.json['items'][2].currentStatus.legacySystemMetadata.network.interfaces[1].ipv4.address}} has instance ID: {{ nginx_server_instances.json['items'][2].metadata.name}}"
        
        
    - name: get Instance ID for gateway1 which is getting DNS resolution from cheese-staging.nginxplus.net
      set_fact:
        gateway1_instance_id: "{{ nginx_server_instances.json|json_query('items[?currentStatus.legacySystemMetadata.network.interfaces[1].ipv4.address == `{}`]|[0].metadata.name'.format(gateway1_target_ip)) }}"

    - name: get Instance ID for gateway2 which is getting DNS resolution from cheese.nginxplus.net
      set_fact:
        gateway2_instance_id: "{{ nginx_server_instances.json|json_query('items[?currentStatus.legacySystemMetadata.network.interfaces[1].ipv4.address == `{}`]|[0].metadata.name'.format(gateway2_target_ip)) }}"

    - name: get Instance ID for api backend which is getting DNS resolution from apibackend.nginxplus.net
      set_fact:
        apibackend_instance_id: "{{ nginx_server_instances.json|json_query('items[?currentStatus.legacySystemMetadata.network.interfaces[1].ipv4.address == `{}`]|[0].metadata.name'.format(apibackend_target_ip)) }}"


    - debug:
        var: gateway1_instance_id, gateway2_instance_id, apibackend_instance_id


    - name: Give the NGINX server 10.0.1.20 a nice working name - NGINX Plus API Gateway 1
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/infrastructure/locations/unspecified/instances/{{gateway1_instance_id}}
        method: PUT
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:          
            metadata:
              name: "{{gateway1_instance_id}}"
              displayName: "NGINX Plus API Gateway 1"
              description: NGINX Plus API Gateway 1
              links:
                rel: "/api/v1/infrastructure/locations/unspecified/instances/{{gateway1_instance_id}}"
        status_code: 200,201,202
        validate_certs: false     

    - name: Give the NGINX server 10.0.1.30 a nice working name - NGINX Plus API Gateway 2
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/infrastructure/locations/unspecified/instances/{{gateway2_instance_id}}
        method: PUT
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:          
            metadata:
              name: "{{gateway2_instance_id}}"
              displayName: "NGINX Plus API Gateway 2"
              description: NGINX Plus API Gateway 2
              links:
                rel: "/api/v1/infrastructure/locations/unspecified/instances/{{gateway2_instance_id}}"
        status_code: 200,201,202
        validate_certs: false     

    - name: Give the NGINX server 10.0.1.90 a nice working name - NGINX Plus API Backend
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/infrastructure/locations/unspecified/instances/{{apibackend_instance_id}}
        method: PUT
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:          
            metadata:
              name: "{{apibackend_instance_id}}"
              displayName: "NGINX Plus API Backend"
              description: NGINX Plus API Backend
              links:
                rel: "/api/v1/infrastructure/locations/unspecified/instances/{{apibackend_instance_id}}"
        status_code: 200,201,202
        validate_certs: false     


    - name: Create Staging Environment
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/services/environments/staging
        method: PUT
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:
          metadata:
            name: staging
            displayName: Staging
            description: 'New Staging Platform for Cheese Application'
            tags: []
          desiredState: {}
        status_code: 200,201
        validate_certs: false



    - name: Install Staging Certificate
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/services/environments/staging/certs
        method: POST
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:
          metadata:
            name: workshop0001.nginxdemo.net
            displayName: workshop0001.nginxdemo.net Wildcard Certificate
            description: All domains residing in *.workshop0001.nginxdemo.net
          desiredState:
            type: PEM
            privateKey: "{{ lookup('file','~/NGINX_API_Automation/certs/workshop0001.nginxdemo.net.key.pem') }}"
            publicCert: "{{ lookup('file','~/NGINX_API_Automation/certs/workshop0001.nginxdemo.net.crt.pem') }}"
            password: ''
            caCerts:
            - "{{ lookup('file','~/NGINX_API_Automation/certs/workshop0001.nginxdemo.net.issuer.pem') }}"
        status_code: 201,409
        validate_certs: false


    - name: Update Staging Gateway
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/services/environments/staging/gateways/cheesevtwogateway
        method: PUT
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:
          metadata:
            name: cheesevtwogateway
            displayName: Cheese Gateway V2
            description: New staging platform for Cheese API V2.
          desiredState:
            ingress:
              uris:
                https://cheese-staging.workshop0001.nginxdemo.net: {}
              placement:
                instanceRefs:
                - ref: "/infrastructure/locations/unspecified/instances/{{gateway1_instance_id}}"
              tls:
                certRef:
                  ref: "/services/environments/staging/certs/workshop0001.nginxdemo.net"
                preferServerCipher: DISABLED
                sessionCache: 'OFF'
        status_code: 201,202,409
        validate_certs: false

    - name: Staging - Create JuiceShop Application
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/services/environments/staging/apps
        method: POST
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:
          metadata:
            name: juiceshop
            displayName: Juice Shop Application
            description: A highly vulnerable test webapp to test WAF solutions against
            tags:
            - nibbles
        status_code: 201,409
        validate_certs: false
   




    - name: Staging - Create an App component to enable access to JuiceShop
      uri:
        url: https://{{ controller_domain_name }}/api/{{ controller_api_version }}/services/environments/staging/apps/juiceshop/components/juices
        method: PUT
        headers:
          Cookie: "{{ session.set_cookie }}"
        body_format: json
        body:          
          metadata:
            createTime: '2020-08-13T15:52:54Z'
            kind: components
            links:
              rel: "/api/v1/services/environments/staging/apps/cheesevtwo/components/juices"
            name: juices
            uid: 8f297954-212b-41da-9de6-5f58d37ccd6d
            updateTime: '2020-08-14T11:52:26Z'
          desiredState:
            backend:
              ntlmAuthentication: DISABLED
              preserveHostHeader: DISABLED
              workloadGroups:
                cheesebackend:
                  locationRefs:
                  - links:
                      rel: "/api/v1/infrastructure/locations/unspecified"
                      displayName: Unspecified (default)
                      name: unspecified
                    ref: "/infrastructure/locations/unspecified"
                  uris:
                    http://10.0.1.90:3000:
                      isBackup: false
                      isDown: false
                      isDrain: false
            ingress:
              uris:

                "/":
                  matchMethod: PREFIX
              gatewayRefs:
              - ref: "/services/environments/staging/gateways/cheesevtwogateway"
            logging:
              accessLog:
                state: DISABLED
              errorLog: DISABLED
            security:
              waf:
                isEnabled: FALSE
              rateLimits:
                policy_1:
                  key: "$http_x_real_ip-$request_uri"
                  rate: 1000r/s
                  statusCode: 429
 


        status_code: 200,201,202
        validate_certs: false
        
        
